# Set the prefix from C-b to C-a
set -g prefix C-a
unbind C-b

# Set default Shell to launch
#set-option -g default-shell /usr/bin/fish

# get links working
set -ga terminal-features "*:hyperlinks"

# Set the delay between prefix and command
set -s escape-time 1

# Ensure that we can send Ctrl-A to other apps
bind C-a send-prefix

# Set the base index for windows to 1 instead of 0
set -g base-index 1

# Set the base index for panes to 1 instead of 0
set -w -g pane-base-index 1

# Renumber when a pane is closed
set-option -g renumber-windows on

# Reload the file with Prefix r
bind r \
    source-file ~/.config/tmux/tmux.conf \; \
    display-message "Configuration reloaded"

# Split panes with | and -
bind | split-window -h
bind - split-window -v

# Move between panes with Prefix h,j,k,l
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Quick window selection
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# Pane resizing panes with Prefix H,J,K,L
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Mouse support - set to on if you want to use the mouse
set -g mouse off

# Set the default terminal mode to 256color mode
set -g default-terminal "tmux-256color"

# Override terminal so it displays 32bit RGB color
set -a terminal-overrides ",*256col*:RGB"

# Theme
source ~/.config/tmux/tokyonight_moon.tmux

# Oane border style: single, double, heavy, simple, number.
set -w -g pane-border-lines single

# Add indicators for two-pane setup
set -g pane-border-indicators arrows


# Update the status line every sixty seconds
set -g status-interval 5

# Center the window list in the status line
#set -g status-justify centre
# Enable activity alerts
set -w -g monitor-activity on
set -w -g visual-activity on

# Enable vi keys.
set -w -g mode-keys vi

# Escape turns on copy mode
bind Escape copy-mode

# v in copy mode starts making selection
bind -T copy-mode-vi v send -X begin-selection

# Make Prefix p paste the buffer.
unbind p
bind p paste-buffer

# Shortcut for synchronize-panes toggle
bind C-s set-window-option synchronize-panes

# Split pane and retain the current directory of existing pane
bind _ split-window -v -c  "#{pane_current_path}"
bind \\ split-window -h -c "#{pane_current_path}"

# make session chooser order by name instead of session index
bind s choose-tree -sZ -O name

# Log output to a text file on demand
bind P pipe-pane -o "cat >>~/#W.log" \; display "Toggled logging to ~/#W.log"

bind C-l send-keys 'C-l'

bind O display-popup -d "~/" \
                         -x C -y C -w 50% -h 50% \
                         -e "POPUP=true" -E "bash"

# popup menu
bind e  \
  display-menu -T "Quick Menu" -x C -y C \
    "New Window" n "new-window" \
    "Horizontal Split" - "split-window" \
    "Vertical Split"  | "split-window -h" \
    "Close Pane" x "kill-pane"

# Copy and paste commands
set -s set-clipboard on
set -g copy-command "wl-copy"
#set -g paste-command "wl-paste -n"

# Prefix Ctrl-C takes what's in the buffer and sends it to system clipboard
# via the command stored in the variable.
bind C-c run 'tmux save-buffer - | $copy_command'

# y in copy mode takes selection and sends it to system clipboard via the
# command stored in the variable.
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel '$copy_command'

# Prefix Ctrl-v fills tmux buffer from system clipboard, then
# pastes from buffer into tmux window
bind C-v run-shell '$paste_command | tmux load-buffer - \; paste-buffer'

set -g default-shell /usr/bin/fish
