# Theme
import = [
"~/.config/alacritty/themes/tokyonight_moon.toml",
]

live_config_reload = true

[shell]
program = "/usr/bin/fish"
args = [ "-lc", "eval (zellij setup --generate-auto-start fish | string collect)" ]

[window]
opacity = 0.98
dimensions = { columns = 216, lines = 240 }
padding.x = 12
padding.y = 6
dynamic_padding = true
decorations = "None"
decorations_theme_variant = "None"

[font]
normal.family = "Commit Mono Nerd Font"
bold.family = "Commit Mono Nerd Font"
italic.family = "Commit Mono Nerd Font"
bold_italic.family = "Commit Mono Nerd Font"
size = 12.5
offset = { x = 0, y = 2 }

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true 

[[hints.enabled]]
command = "xdg-open" # On Linux/BSD
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]

